### ISSUE TITLE
DXF files?

### ISSUE THREAD

**Issue by np22-jpg** [MrAlvin/RAMPS_1.7#1]
I really want to make another version of this with integrated TMC2130's and multiple TMC4361A's with an SPI encoder input for closed loop stepping.

**Comment by MrAlvin** [comment]
Okay. What is an TMC4361A?  And how would it be connected to this Arduino Shield?

**Comment by np22-jpg** [comment]
The TMC4361A-LA is an IC offered by Trinamic that adds closed loop functionality to any driver that requires a step/dir signal. As a bonus, it also calculates ramping and positioning so that way the CPU does not have to generate those signals, effectively lessening the strain on the SAM3X8E (which is, by the way, outdated and no longer recommended for newer designs). I imagine that it would connect to the shield in the form of another shield. It would only require 1 extra chip select pin, and adds the availability to use any encoder (SSI, SPI, ABN, ABI, UVW, etc.). It would also be the one to interface with the endstops (if available). Additional functionality includes a NFREEZE pin to freeze all operations in the case of emergency, dcstep inputs for calibration, a 1.8V regulator, and NRST for reset. The only downside is that it only controls 1 axis, so therefore 1 is needed for each axis. Most people use and ATMEGA328PA as a replacement for this IC, however this IC handles this with 32-bit logic and much more precision.

**Comment by np22-jpg** [comment]
I want a DXF file so I have an outline to work with to make this shield, and the program I use you can only import .svg or .dxf files for board outlines and footprints.. The shield will also feature an LCD connector. Technically, the IC can be used to retrofit any motor driver, so the board should still be compatible with the DRV8825's and the A4988 and any other 3.3V or 5V driver.

**Comment by MrAlvin** [comment]
I see. That does indeed sound very interesting. Unfortunately the program I work with, can only export gerber files or pictures. 
Using a picture, was the way I moved from the RAMPS 1.4 design, to this RAMPS 1.7 design, as I am using a different PCB design program.

**Comment by np22-jpg** [comment]
Alright. I'll figure it out :) I'll just wait until the final version is released in order to make my shield. Thanks. What I can do is export the PDF, match it up with a mega, and make a sketch. Then I can finally export it as a .dxf file. The reason I wanted one directly was because this is very tedious and is often unreliable.

**Comment by np22-jpg** [comment]
One last question before I close this issue forever, will the board maintain it's current dimensions and pin hole locations? It would be nice to not remake my PCB after you make your final revision for the first production version.

**Comment by MrAlvin** [comment]
hmmm.... good question. 

The max size is 100 x 100 mm, and on one side, this max was reached on day one. And it seems that from time to time, I add a few millimeters, to accommodate the latest discovery/needed-adjustment/better design-idea. 

I would like to re-design the entire mosfet area, as there are a few components that are with a rather tight fit.  But this would be a lot of work, so for now, I just leave it be. 

 Either way; so far I seem to have made small adjustments about every week or so. 

The four main influences to cause adjustments have so far been:

- because things look good on paper, does not mean that it feels right when you have the thing in your hands ..... and need to plug stuff in.  There may be room on paper, but it would simply be more smooth if this or that small adjustment was made. 

- a design decision, made when things were first designed, may turn out to be better, if adjusted slightly, when I give it a second or third overhaul, or look deeper into details.

- making the Marlin firmware work.  As I have needed to dig in deeper under the hood of Marlin, I discover new things.  
Like, this week, I have for instance made adjustments so it would be much easier to also use the shield with the Re-ARM MCU board. 

- I have been working on adding functionality to the LCD board. Mainly so the entire LCD and buttons section can be controlled via I2C or SPI I/O-expanders. But this work has spun up more ideas, like; 
-- what if  an ESP-01 connector could be added to the main board? 
-- and what if temperature sensors could be made to be able to handle volt abuse, like; 24V applied to either of the two wires to the temperature sensor to have no effect of the MCU. That would be a rather nice addition. 
--servo pin 3 and 4 have dual functionality. What if the re-arranging of the mosfet-section, also caused there to be room for easy jumper connectors to move some functionality to freed pins on aux-4, now that the LCD is being handled by I/O-expanders. 
-- what if I/O-expanders, especially SPI I/O-expanders were added to some of the fewer-pin-count 32-bit processors, would it then be possible to use 4-5 dollar MCU's to control the board. And would this cause me want to make adjustments to the RAMPS 1.7 board?
-- what if a universal I/O-expander, like an atmega88, were added to the mix, would it then be feasible to monitor voltages and fuses? 

Yes, stuff like that seems to creep in, and cause the board to sometimes grow a little, in the one direction where there is still room to grow.

What is however set in stone, is:
- the Arduino pins layout. 
- the correlation of placement between Aux-3 and Aux-4.  The most common LCD adapter, uses both these ports, and it MUST be possible to use that adapter board with a RAMPS-named board. 
- the stepper drivers are not going to move....... Unless - the mosfet-section gets a makeover. As it would be nice to move the X,Y,Z stepper section about 1mm away from the Aux-2 / Aux-4 section. 


So, does this answer your question? 

Are there any particular connectors that you are more interested in, to not move?

**Comment by np22-jpg** [comment]
No. That's it. Thanks. I'd rather this shield not change and mine to change a LOT so that you're not restricted. If you had to accommodate for everybody, then nothing would get done. I'll start doing BOM, then I'll do PCB design later down the line when you have the final layout. If you do change the layout in the future after I made my shield, then I'll change the layout of mine. I really do believe in the philosophy of a modular system with bits that can be changed. I got so triggered when apple started soldering their RAM and SSD's straight to the board.

**Comment by np22-jpg** [comment]
Oh btw the free (so professional) program that I use is cloud based, and you can oversee my project if you so desire:
here:https://easyeda.com/npgoalkeeper/ramps1-7
It will feature an LCD connector, the stuff I said earlier, but no connector for stepsticks, I want to be able to use dcstep which has has an output that is not broken out. Also, no current scaling at all, similar to a RAMBo if there's space for it (Unless you want to use stallguard/dcstep/coolstep)
Also, I won't  close this issue. I clearly keep changing my mind.

**Comment by np22-jpg** [comment]
For the regulator, should I add a Ti Power Monitor along with a flyback converter controller and n-ch mosfets? The output would be able to change from 5v to 3.3v with a very small tolerance (around 3 percent of I recall correctly). Otherwise, I will just stick with the lm2576 linear regulator.
